name: Keep Alive

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Streamlit
        run: curl -L -s -o /dev/null "https://itc-deportes.streamlit.app/" || true
