[theme]
   primaryColor = "#C9A227"
   backgroundColor = "#0E1712"
   secondaryBackgroundColor = "#16211B"
   textColor = "#F5F7F5"
   font = "sans serif"

[server]
   folderWatchList = ["src"]
   runOnSave = true
